# channels.pyi
# Type stub for FL Studio channels scripting module.

def channelCount() -> int: ...
def getChannelName(index: int) -> str: ...
def setChannelName(index: int, name: str) -> None: ...
def getChannelVolume(index: int) -> float: ...
def setChannelVolume(index: int, volume: float) -> None: ...
def getChannelPan(index: int) -> float: ...
def setChannelPan(index: int, pan: float) -> None: ...
def muteChannel(index: int, value: int = ...) -> None: ...
def isChannelMuted(index: int) -> bool: ...
def soloChannel(index: int, value: int = ...) -> None: ...
def isChannelSoloed(index: int) -> bool: ...
def getTargetTrack(index: int) -> int: ...
def setTargetTrack(index: int, trackIndex: int) -> None: ...
def midiNoteOn(index: int, pitch: int, velocity: int) -> None: ...
def selectChannel(index: int, value: int = ...) -> None: ...
def isChannelSelected(index: int) -> bool: ...
def selectAll() -> None: ...
def deselectAll() -> None: ...
