# device.pyi
# Type stub for FL Studio device scripting module.

def setHasMeters() -> None: ...
def midiOutSysex(port: int, channel: int, data: bytes) -> None: ...
def midiOutMsg(msg: int) -> None: ...
def getPortNumber() -> int: ...
def getName() -> str: ...
