# general.pyi
# Type stub for FL Studio general scripting module.

def processRECEvent(index: int, value: int, flags: int) -> int: ...
def processMIDICC(index: int, value: int, flags: int) -> int: ...
def undoUp() -> None: ...
def undoDown() -> None: ...
def getVersion() -> str: ...
def undo() -> None: ...
def getUndoHistoryCount() -> int: ...
def getUndoLevel() -> int: ...
