# mixer.pyi
# Type stub for FL Studio mixer scripting module.

def trackCount() -> int: ...
def getTrackName(index: int) -> str: ...
def setTrackName(index: int, name: str) -> None: ...
def getTrackVolume(index: int) -> float: ...
def setTrackVolume(index: int, volume: float) -> None: ...
def getTrackPan(index: int) -> float: ...
def setTrackPan(index: int, pan: float) -> None: ...
def muteTrack(index: int, value: int = ...) -> None: ...
def isTrackMuted(index: int) -> bool: ...
def soloTrack(index: int, value: int = ...) -> None: ...
def isTrackSoloed(index: int) -> bool: ...
def getRouteSendActive(fromTrack: int, toTrack: int) -> bool: ...
def setRouteSendActive(fromTrack: int, toTrack: int, active: bool) -> None: ...
