# patterns.pyi
# Type stub for FL Studio patterns scripting module.

def patternNumber() -> int: ...
def patternCount() -> int: ...
def jumpToPattern(index: int) -> None: ...
def getPatternName(index: int) -> str: ...
def setPatternName(index: int, name: str) -> None: ...
def getPatternLength(index: int) -> int: ...
def setPatternLength(index: int, length: int) -> None: ...
def getPatternColor(index: int) -> int: ...
def setPatternColor(index: int, color: int) -> None: ...
def getActivePattern() -> int: ...
def selectPattern(index: int) -> None: ...
