# playlist.pyi
# Type stub for FL Studio playlist scripting module.

def trackCount() -> int: ...
def getTrackName(index: int) -> str: ...
def setTrackName(index: int, name: str) -> None: ...
def muteTrack(index: int, value: int = ...) -> None: ...
def isTrackMuted(index: int) -> bool: ...
def soloTrack(index: int, value: int = ...) -> None: ...
def isTrackSoloed(index: int) -> bool: ...
def selectTrack(index: int) -> None: ...
def getSelectedTrack() -> int: ...
def getLiveState() -> int: ...
