# transport.pyi
# Type stub for FL Studio transport scripting module.

def start() -> None: ...
def stop() -> None: ...
def isPlaying() -> bool: ...
def isRecording() -> bool: ...
def record() -> None: ...
def getSongTempo() -> float: ...
def globalTransport(command: int, value: int) -> None: ...
def getSongPos(mode: int = ...) -> int: ...
def setSongPos(pos: int, mode: int = ...) -> None: ...
def getLoopMode() -> int: ...
def setLoopMode(mode: int) -> None: ...
