# ui.pyi
# Type stub for FL Studio ui scripting module.

def save() -> None: ...
def showWindow(windowId: int) -> None: ...
def isWindowVisible(windowId: int) -> bool: ...
def getFocusedWindow() -> int: ...
def setFocusedWindow(windowId: int) -> None: ...
def showWindowCommand(windowId: int, command: int) -> None: ...
def getVisibleRect(windowId: int) -> tuple[int, int, int, int]: ...
def crDisplayRect(windowId: int, left: int, top: int, right: int, bottom: int) -> None: ...
